### PR TITLE
Update README.txt

### PR DESCRIPTION
**Pull request by devpreview**
Removed depricated drupal_mail function.

### CODE REVIEW

**Comment by webflo** [comment]
`language_default()` does not exists anymore. Could you use the language manager instead?

**Comment by devpreview** [comment]
Done.

**Comment by webflo** [comment]
https://www.drupal.org/node/2616458

**Comment by webflo** [comment]
Committed to the drupal.org repo. https://www.drupal.org/commitlog/commit/22794/3b592267816dc95488c32f6679d844cd034c839b

Thanks!

**Pull request closed without merging**
